### ISSUE TITLE
Spiritual Weapon 'flags' field undefined.

### ISSUE THREAD

**Issue by Onahail** [kandashi/midi-srd#37]
`MidiSRD-macros.js:2224 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'flags')
    at MidiMacros.spiritualWeapon (MidiSRD-macros.js:2224:42)
    at Proxy.eval (eval at callMacro (workflow.js:1733:17), <anonymous>:3:12)
    at Workflow.callMacro (workflow.js:1734:16)
    at Workflow.callMacros (workflow.js:1594:21)
    at Workflow._next (workflow.js:973:18)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)`

Found when attempting to use the spell after applying Midi SRD Automation.

**Comment by thatlonelybugbear** [comment]
Same as per https://github.com/kandashi/midi-srd/issues/38
