### ISSUE TITLE
Problem with compendium-folders?

### ISSUE THREAD

**Issue by geoidesic** [kandashi/midi-srd#9]
I'm using v9.x and I tried for example to cast Misty Step (which has AE flag and came from midi-srd). I notice the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'folders')
[Detected 2 packages: compendium-folders, sequencer]
    at Function.importFolderData (modules/compendium-folders/fic-folders.js:1469:52)
    at modules/compendium-folders/fic-folders.js:472:34
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10254:13)
    at foundry.js:10193:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10193:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:10074:17)
    at async Function.updateDocuments (common/abstract/document.mjs:373:21)
    at async Scene.update [as __compendium_tools_original_update] (common/abstract/document.mjs:456:21)
    at async Object.<anonymous> (modules/sequencer/scripts/module/flag-manager.js:237:13)
```

**Comment by kandashi** [comment]
Module is not updated for v9
